# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cloudsync}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Cory Forsyth"]
  s.date = %q{2010-10-12}
  s.default_executable = %q{cloudsync}
  s.description = %q{TODO: longer description of your gem}
  s.email = %q{cory.forsyth@gmail.com}
  s.executables = ["cloudsync"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/cloudsync",
     "lib/cloudsync.rb",
     "lib/cloudsync/backend/base.rb",
     "lib/cloudsync/backend/cloudfiles.rb",
     "lib/cloudsync/backend/s3.rb",
     "lib/cloudsync/backend/sftp.rb",
     "lib/cloudsync/datetime/datetime.rb",
     "lib/cloudsync/file.rb",
     "lib/cloudsync/sync_manager.rb",
     "lib/cloudsync/version.rb",
     "test/helper.rb",
     "test/test_cloudsync.rb"
  ]
  s.homepage = %q{http://github.com/bantic/cloudsync}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{TODO: one-line summary of your gem}
  s.test_files = [
    "test/helper.rb",
     "test/test_cloudsync.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<right_aws>, [">= 0"])
      s.add_runtime_dependency(%q<cloudfiles>, [">= 0"])
      s.add_runtime_dependency(%q<commander>, [">= 0"])
    else
      s.add_dependency(%q<right_aws>, [">= 0"])
      s.add_dependency(%q<cloudfiles>, [">= 0"])
      s.add_dependency(%q<commander>, [">= 0"])
    end
  else
    s.add_dependency(%q<right_aws>, [">= 0"])
    s.add_dependency(%q<cloudfiles>, [">= 0"])
    s.add_dependency(%q<commander>, [">= 0"])
  end
end

