# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cloudsync}
  s.version = "2.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Cory Forsyth"]
  s.date = %q{2010-10-14}
  s.default_executable = %q{cloudsync}
  s.description = %q{Sync files between various clouds or sftp servers. Available backends are S3, CloudFiles, and SFTP servers. Can sync, mirror, and prune.}
  s.email = %q{cory.forsyth@gmail.com}
  s.executables = ["cloudsync"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/cloudsync",
     "cloudsync.gemspec",
     "lib/cloudsync.rb",
     "lib/cloudsync/backend/base.rb",
     "lib/cloudsync/backend/cloudfiles.rb",
     "lib/cloudsync/backend/s3.rb",
     "lib/cloudsync/backend/sftp.rb",
     "lib/cloudsync/datetime/datetime.rb",
     "lib/cloudsync/file.rb",
     "lib/cloudsync/sync_manager.rb",
     "test/helper.rb",
     "test/test_cloudsync.rb"
  ]
  s.homepage = %q{http://github.com/megaphone/cloudsync}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Sync files between various clouds or sftp servers.}
  s.test_files = [
    "test/helper.rb",
     "test/test_cloudsync.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<right_aws>, ["~> 2.0.0"])
      s.add_runtime_dependency(%q<cloudfiles>, ["~> 1.4.8"])
      s.add_runtime_dependency(%q<commander>, ["~> 4.0.3"])
      s.add_runtime_dependency(%q<net-ssh>, ["~> 2.0.19"])
      s.add_runtime_dependency(%q<net-sftp>, ["~> 2.0.4"])
      s.add_runtime_dependency(%q<escape>, ["~> 0.0.4"])
    else
      s.add_dependency(%q<right_aws>, ["~> 2.0.0"])
      s.add_dependency(%q<cloudfiles>, ["~> 1.4.8"])
      s.add_dependency(%q<commander>, ["~> 4.0.3"])
      s.add_dependency(%q<net-ssh>, ["~> 2.0.19"])
      s.add_dependency(%q<net-sftp>, ["~> 2.0.4"])
      s.add_dependency(%q<escape>, ["~> 0.0.4"])
    end
  else
    s.add_dependency(%q<right_aws>, ["~> 2.0.0"])
    s.add_dependency(%q<cloudfiles>, ["~> 1.4.8"])
    s.add_dependency(%q<commander>, ["~> 4.0.3"])
    s.add_dependency(%q<net-ssh>, ["~> 2.0.19"])
    s.add_dependency(%q<net-sftp>, ["~> 2.0.4"])
    s.add_dependency(%q<escape>, ["~> 0.0.4"])
  end
end

